version: '3.7'
services:
  web:
    container_name: found-offer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    environment:
      - FLASK_DEBUG=1
    ports:
      - 5000:5000
    env_file: ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: found-offer

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "-A", "make_celery:celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis
    restart: "on-failure:2"

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "-A", "make_celery:celery_app", "beat", "--loglevel=INFO"]
    depends_on:
      - redis
      - celery_worker
    restart: "on-failure:2"
